Fix issue #283: Rename Key Group to Entity Set
PennLINC/CuBIDS pull request #329
Opened 2024-10-04 20:04 UTC by tientong98

Closes .

## Changes proposed in this pull request

- Use re to change all instances of Key Group ('([Kk])ey(\s*|_)([Gg])roup') to Entity Set (matching capitalization and delimiter) across all files that can be decoded using UTF-8.

2024-10-04 21:39 UTC, tientong98 commented
Hi @tsalo and @mattcieslak - circleci failed because it used ubuntu-2004:202201-02, which is now [deprecated and not available ](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177). I want to change the config.yml file so that it uses one of the [current images](https://discuss.circleci.com/t/ubuntu-20-04-22-04-24-04-q3-current-release/51856), but I'm not sure if it will break anything else. Do you have any preference on which image to use?

2024-10-04 23:43 UTC, mattcieslak commented
Any of those should be ok

2024-10-09 15:03 UTC, tsalo requested changes
Just one requested change. Also, this is a breaking change, so I'd add a `breaking-change` label to the PR and we need to make sure the next release is a major one.

2024-10-09 15:03 UTC, tsalo commented on HISTORY.rst
> +* adding note about fmap renameentitysets by @megardn in https://github.com/PennLINC/CuBIDS/pull/140
We shouldn't modify the changelog.

2024-10-09 16:02 UTC, tsalo approved these changes
LGTM!

2024-10-09 17:02 UTC, mattcieslak approved these changes
Excellent!! I like the new name much better

2024-10-09 17:02 UTC, mattcieslak commented on docs/usage.rst
>  ~~~~~~~~~
```suggestion
~~~~~~~~~~~
```

2024-10-10 14:08 UTC, merged