PR addressing issues I raised recently
PennLINC/CuBIDS pull request #346
Opened 2024-12-20 17:25 UTC by gabridele

Hi there,

I’m submitting this pull request to address a few issues I came across while using the library. Before submitting, I ran tests as outlined in the documentation to ensure everything works as expected.

## Changes proposed in this pull request

This pull request aims to resolve the following issues:

- #340 
- #341 
- #342 

## Documentation that should be reviewed

Based on these changes, no updates to the existing documentation are needed.

Feel free to reach out if you have any questions or need further clarification on my edits!

2025-01-14 15:26 UTC, tsalo requested changes
I'd prefer to figure out what's going wrong with `IsFile` and `PathExists` than to replace them with `Path`. Can you drop those changes but keep the rest?

2025-01-14 16:30 UTC, gabridele commented
Hi,
I restaged all of my edits, thought it would be a cleaner way of doing it. Dropping those two commits and then forcefully pushing the edits created like 20 more commits. So I reset the head to match your main branch and re-committed the edits. I'm sure there's a less cumbersome way, but I'm not that experienced with PRs. Sorry about that

2025-01-14 16:31 UTC, gabridele commented on cubids/cubids.py
> +        if "/" not in str(exemplars_tsv):
Good point! I edited it according to your suggestion

2025-01-14 16:45 UTC, tsalo approved these changes
The changes look good to me. I think you just need to link the associated issues with `closes #...` so that they close when we merge your PR.

2025-01-14 16:52 UTC, gabridele commented
@tsalo done! added them in my first message

2025-01-14 16:53 UTC, tsalo commented
Perfect. Once CI passes, I'll merge.

2025-01-14 17:04 UTC, merged

2025-01-15 14:48 UTC, tientong98 commented
@gabridele does this PR close https://github.com/PennLINC/CuBIDS/issues/340?

2025-01-15 14:49 UTC, tsalo commented
No, @gabridele dropped that element at my request.